### ISSUE TITLE
Publish a list of implementations

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson-text-sequences#1]
Some implementations: [Rasterio](https://github.com/mapbox/rasterio), [Fiona](https://github.com/Toblerity/Fiona).

Candidates: geojsonio, Turf.

**Comment by perrygeo** [comment]
While not necessarily an application itself, [cligj](https://github.com/mapbox/cligj) can adapt python CLIs to accept feature sequences. 

Since it's a purpose-built geojson argument parser, a simple app built on cligj might make a good reference implementation (particularly [this example](https://github.com/mapbox/cligj#example) since it serves as both a sequence reader and writer)

**Comment by dret** [comment]
On 2016-03-01 12:21 , Matthew Perry wrote:

> While not necessarily an application itself, cligj
> https://github.com/mapbox/cligj can adapt python CLIs to accept
> feature sequences.

i don't think implementations need to be applications. they very well 
might be parsers/libraries, consuming/producing sequences and allowing 
applications to interact with them through some API.

**Comment by martinthomson** [comment]
This info is probably better maintained on the wiki so that the list can be presented coherently.  If you indeed intend to maintain a list.

For me, I'm fairly satisfied with the list already here.  I think we have enough to ask the IESG to publish the doc.

**Comment by sgillies** [comment]
https://github.com/geojson/geojson-text-sequences/wiki/Implementations
