### ISSUE TITLE
Allow the first record to be a FeatureCollection?

### ISSUE THREAD

**Issue by mpdaly** [geojson/geojson-text-sequences#13]
Although FeatureCollection objects only contain an array of Feature objects by default, "foreign members" are allowed, which would be lost in a GeoJSON -> GeoJSON TS -> GeoJSON workflow.

Additionally, the FeatureCollection "features" member could be allowed to be:
1. null, or,
2. if known, an integer representing the number of Feature object records that follow

**Comment by sthagen** [comment]
@mpdaly: I still try to wrap my head around the above 1) "Although ..." and 2) "Additionally ..." statements. 

Ad 1) with "foreign members" meant are instances like the sub tree starting with '"foo": ' in:
 `{ "type": "FeatureCollection", "features": null, "foo": {"bar": "baz} }` - correct? My understanding would be, that in a  GeoJSON(1) -> GeoJSON TS -> GeoJSON(2) workflow, the consumer GeoJSON(2) decides on what to keep and what to drop - or did I overlook something obvious?

Ad 2) Why would it be a problem for framing GeoJSON texts with RECORD SEPARATOR and NEWLINE to build a GeoJSON Text Sequence, when the features member is null or a number - as an example:
`RS { "features": null, "type": "FeatureCollection" } NL RS { "type": "FeatureCollection", "features": 42 } NL`
Or does this second point mean, it would be a feature of breaking a single fat GeoJSON "entity" into a flat lean sequence, where like a header the initial FeatureCollection advertises eg. 42 or unlimited Feature objects that would follow as RS/NL framed elements? 

Sorry if these questions are obvious to answer ...

**Comment by sgillies** [comment]
@mpdaly @sdrees as the draft stands, a sequence record can be any GeoJSON type (Feature, Geometry, FeatureCollection), so you can write a sequence with a leading FeatureCollection. We don't have any specification for what the first record means to following records and the draft currently warns against giving significance to the order of records in a sequence.

For a while, I thought that a "header" record could be useful. But as I think about applications of GeoJSON sequences, I feel that headers or other metadata about a sequence are best communicated out of band. In the case of an infinite sequence, for example, the header is too far in the past to be of use to a reader that attaches to the sequence late. Requiring a header also complicates distributed analysis of features in a sequence as it gets in the way of using generic streaming applications like GNU parallel and Hadoop streaming.

It might be that the semantics of a FeatureCollection is the thing that makes a geo+json-seq media type worth defining and that geo+json-seq should be not about infinite sequences at all, but only be about very large but finite, incrementally parseable FeatureCollections.

**Comment by mpdaly** [comment]
@sgillies @sdrees This had fallen off my radar somewhat...

Plus, I think that I wrote it before we nailed down what was meant by a "GeoJSON type".

Whatever the draft says, README.md states:

"A GeoJSON Feature Sequence is a document containing, instead of a single GeoJSON Feature Collection, multiple GeoJSON Feature texts that can be parsed and produced incrementally."

That appears at odds with the draft.

I'm concerned (conceptually, not practically, to date) with the FeatureCollection foreign members, not with metadata about the sequence (eg my 2, above, which was just a sort-of obvious thing to suggest). A leading FeatureCollection with `"features": null` would satisfy my foreign member concerns (while bearing in mind your valid distributed processing point).

I definitely wouldn't want to require it, and it is already allowed (even if only by implication). If README.md is corrected, and a little guidance (with caveats) is given in the spec, then that would be more than enough for me.

**Comment by sgillies** [comment]
@sdrees rereading your comment, it looks like you're asking whether or not a parser must understand that there are multiple FeatureCollections in a sequence, is that right? This seems to be to be a hard thing to do, especially since text sequences are intended to withstand the type of serialization failures that happen in distributed systems. Corruption of the leading or subsequent FeatureCollection text could happen, and then what would be the interpretation of following features?

Let's have this discussion on the list.

**Comment by dret** [comment]
as a general remark/reminder: the initial idea https://github.com/geojson/draft-geojson/issues/64 was not about using sequences as an alternative way to serialize one large object. the idea was mostly to provide a way how multiple objects can be serialized in a way that does not require them to be packaged in a new and artificial GeoJSON-level container.
while "sequences" is used as a term (because that's what the underlying spec is called), logically these should be considered collections (i.e., unordered and not even necessarily sets). if applications choose these as some kind of "alternative GeoJSON container", then the resulting problems are something these applications have to figure out.
