### ISSUE TITLE
Only "Feature" objects?

### ISSUE THREAD

**Issue by dret** [geojson/geojson-text-sequences#5]
if this is only going to only allow feature objects (i.e., none of the other GeoJSON object types), then it would be good to say why, and what's supposed to happen if other GeoJSON object types are encountered while parsing.

**Comment by sgillies** [comment]
@dret our first major question, for sure! I started with features because that's my immediate use: turning the gigantic GeoJSON feature collections I see at work into incrementally process-able sequences.

I think there are at least 3 sub-questions:
1. are sequences of geometries useful and interoperable? (possible/likely)
2. are sequences of feature collections useful and interoperable? (I think not, because of the issue of data bulk)
3. are mixed sequences (geometries _and_ features) useful and interoperable (I think not)

I'll take this to the list as soon as I've uploaded version -01 of the GeoJSON draft and got that off our plates. I'm also very interested in running this by the JSON list and Cullen Jennings since it has some things in common with https://datatracker.ietf.org/doc/draft-jennings-core-senml/.

**Comment by dret** [comment]
On 2016-03-01 5:42 , Sean Gillies wrote:

> I think there are at least 3 sub-questions:
> 1. are sequences of geometries useful and interoperable? (possible/likely)
> 2. are sequences of feature collections useful and interoperable? (I
>    think not, because of the issue of data bulk)
> 3. are mixed sequences (geometries /and/ features) useful and
>    interoperable (I think not)

i'd approach this from the angle of "what can you gain by constraining 
the set of allowed objects?" if there are additional issues (such as how 
to communicate a bbox "out of band"), then it may be worthwhile to make 
sure that the scenarios are more tightly controlled. if all that this 
spec is going to say is pretty much what the media type is if you stream 
GeoJSON objects as JSON text sequences, then maybe the easiest way to do 
this is to allow any GeoJSON, and let implementations decide which ones 
they're going to use.

**Comment by sgillies** [comment]
While I think sequences of GeoJSON Feature objects _only_ are going to be the most useful kind of sequence, I don't think there's any reason to constrain the records to be of a single type.

@dret if you don't mind, I'll change the title of the draft to "GeoJSON Text Sequences" to reflect this.

**Comment by dret** [comment]
On 2016-03-14 20:16, Sean Gillies wrote:

> @dret https://github.com/dret if you don't mind, I'll change the title
> of the draft to "GeoJSON Text Sequences" to reflect this.

sounds good to me, and i think this makes more sense than creating a 
specific subset of geojson and only allow that in the sequences.

as long as there aren't that many people watching it, you may want to 
change the name of the repo as well, so that it matches the draft's title.
